* 知乎
** 回答一
以前有个小朋友，特别喜欢吃冰糖葫芦，每天放学都要爸爸买一根；他爸爸为了戒掉他这个坏习惯，有一天一次买了十根；头两根很好吃，可是吃到第三根的时候就厌了，第四根就完全吃不下了，爸爸也帮忙吃，两人最后腻死吃完十根；自那以后，这个小朋友看到冰糖葫芦就想吐。

“少吃多滋味，多吃伤脾胃”，这是我外婆常说的一句俏皮话。

喜欢也是一样，它是由内而外的一种情感满足，没有办法从外部强加，却很容易从内部消减。

喜欢喝可乐多于牛奶，真的只是因为可乐比牛奶好喝吗？表面上看起来是的，因为这种喜欢天生就存在，但正是由于如此，它很容易由喜欢变为厌恶，办法很简单，就是反复无限次重复，天天喝顿顿喝，你还会喜欢吗？

我曾经问过好多人一个问题，如果现在就让你财务自由，明天开始就不用上班，你每天会选择干嘛？有人会说，太好了，我终于可以有钱有时间干我喜欢做的事了。喜欢做的事？比如呢？比如逛街看电影，吃好多好吃的，去旅游，去滑雪，去潜水，去跳降落伞。那再之后呢？再之后……实在是想不到什么了。滑雪，潜水，旅游，看起来是丰富多彩的，可真的当这些变成你生活中的一部分之后，那么它们跟你现在可以做的爬山、跑步又有什么不同呢？你现在爬山跑步可以坚持天天做吗？你说喜欢逛街吃饭看电影，每天这样的生活，估计不到半年你就腻了吧。还有几十年，你打算做什么呢？这可能就是为什么很多刚退休的人最容易得忧郁症的原因吧。

绝对角度的喜欢，是很难去定义的。表面上看起来喜欢的事，其实都是可以通过反复无限次重复，降低你对它的好感度。人类真正所喜欢的并不是事物本身，而是一种新鲜丰富且舒适的生活状态，可是，一旦这种状态无法持续，喜欢的事物就会变得厌恶。

人，既难获得满足，又怕失去追求。

有的人喜欢看乒乓球，可是中国队老是赢，很快就觉得没意思了；刘翔跑了第一，又开始追跨栏，结果刘翔几次退赛，就开始谩骂；丁俊晖打出了名气，家长们又开始逼着自己的孩子模仿小丁模式，一窝蜂地弃学练球；恒大搞好了一只足球队，一夜间又多出了无数中超球迷，你会发现可能其中就有很多之前谩骂过中国足球的人。

而我从小就喜欢看国足，这么多年也没改变过。虽然这种喜欢遗憾时多，快乐时少，但哪怕是一次小小的胜利，甚至小小的改变，我都会获得莫大的喜悦与满足。或许正是因为如此，我才从来没有对这种喜欢产生厌恶。

痛快痛快，无痛不快；不经历过波折，又怎么能体会成功带来的快乐，又怎么会珍惜自己不喜欢事物的美好？

所以，喜欢无法从外部强加，却可以跟幸福一样，通过相对比较降低期望值来获得满足。每天只吃粗茶淡饭，没有油水，没有零食，说不得某一天，你或许就会突然喜欢上喝牛奶了呢。
** 回答二
主要问题是你没有危机感，你要做的事情不是“不做会死”或者“过了deadline会死”的情况。工作了之后，很多事情失误了或过时了就会死得很惨，你自然不会去怠慢。而只要事情的缓急能够给你哪怕一分钟的空间，你一定会再打一分钟哪怕是扫雷来拖够这一分钟。到了不干不行的份上你一定不会再玩的。

看文献完全就是一件你自己打算做的事情。做还是不做都是自己跟自己商量。世界上最好商量的人就是自己了。你准备早上一过去就看文献，事实上你过一小时也能看，下午也能看，晚上也能看。如果一件事情是领导下达的任务，哪怕没有deadline，你如果不是马上干这件事的话，领导走出来看到你在干别的，你怎么回应？你手头上还有之前的更紧急的事情？还是你觉得领导的任务可以拖一拖？事实上很可能你身上根本就有干不完的一堆事情，必须分门别类，

我个人觉得这不是某天采用了某个方法“pia”一下就转变过来的，是跟一个人的成长有关。一来是对自己的了解程度有限，有时你自己以为你很快做完某事，结果花了很长时间你都没料到。这是需要你长期有意识地在做事中了解自己才能改善的。至于acfun和zhihu，等你觉得这些东西的意义比起你本职工作而言实在低到一个程度，你就不会有事没事去check它们了。Facebook上面那些游戏，它的设计就是需要你每一小时上去玩一下。例如烹饪的游戏，你一定要煮一个什么才能升级，煮那个要1小时，一小时之后你必须去点一下那个“完成”，否则过了多少分钟就糊了，重煮。除了1小时的，还有要30min的、45min的。渐渐地你找不到什么仁慈的游戏是随便你什么时候登录玩一下都一样升级的了。社交网站就是恨不得你每一秒钟都粘在上面。看穿了之后你还会完这类游戏吗？什么“金币”、“赞同数”、“声望”什么的，都是类似的伎俩而已。当然，人有七情六欲，有娱乐、获得肯定的需要。但你完全可以挑那种不讲求“用户粘度”的地方娱乐和刷存在感。

另外，建议你忘掉那些“新概念web2.0GTD蕃茄工作法……”问题并不出在你没用这些方法，而是出在你的思想中。治精神病也有行为矫正疗法，但那是为了变回正常人。

以上是泛泛而谈，下面具体评论一下你列的几种情况，但仅为评论，有助于你更明确，但没有特别的解决办法。

1. 关于刷acfun和zhihu
以我的例子就是微博、豆瓣等。
把那些“未读信息提醒”类的插件卸载掉。我为什么要第一时间知道“你的一位朋友回复了你的评论，快去看看！？？？工作有工作的时间，社交有社交的时间。如果你有FaWave插件一定要卸。我现在是靠微博经营求生么？人生最重要的事情是微博么？既然不是，使所有微博帐号都同步真有这么重要么？自从我把它卸了之后，世界清静多了。类似的，桌面版的所有“客户端”都卸了吧。当你决定玩社交网站，你就相当于决定浪费过多时间在社交网站。社交网站的设计就是你如果不沉迷的话就没有意思了，越沉迷它反而越回馈你以成功感和实惠（星级、VIP、达人）。

至于zhihu，我没有把zhihu当成一个“获得新新生活科技小冷常酷识果壳煎蛋松鼠会”的地方。我关注的人不算多，真正活跃的更少，所以我的时间线更新频率很慢。我基本上时间是花在回答问题，我的答案都是长到不问内容就可以折叠的程度的。不过知乎答案可以保存，我不会耽误正事。

2. 调试软件
可分为两类。
a. 与工作无关
没过一段时间你又琢摩着重装系统吧？内存加一下？最近对开源软件感兴趣，想把机子里的都换成开源的，明明PhotoShop用熟了，非用Gimp。结果到用的时候才知道麻烦。手机安卓4.04的想升到4.1？OriginPro出SR6了，我才SR5，要升级一下？……种种这些的性质是属于你工作之外的，仅仅是因为你对折腾这些东西感兴趣。所以，你不能自己骗自己说“这些事情能提高你的工作效率”。
b. 与工作有关
例如如何使用OriginPro。刚读研就会遇到“什么都要学”的问题，做实验怎么配样品要学、测试仪器怎么用要学、数据怎么处理要学，OriginPro要学、MATLAB要学。如果你实验要用OriginPro的某个功能，你花很多时间学这个功能，这当然不算浪费时间。你如果觉得泄气可能是因为你之前没料到时间要花这么多，但这是你必须经历的。用软件还有sense的问题。有的人用软件的sense很差，没有触类旁通的思维，学用一个软件非常慢。有的人就可能学得快些。这说明你要了解你自己是哪种，一开始你就要能预料到：哇，不懂用Origin作3D图，那估计今天这事情是搞不完了。而不是搞到晚上才发现今天没进展很泄气。

3. crossref
看文献是一个学习的过程。很多事情是看了文献才知道的，知道了之后事情性质又不一样了，问题也不一样了，你又要按新的认识来查找文献了……到头来光是你的基本认识就一直没确立，只有基本阅遍了一个研究方向的所有文献，你才有一个比较符合主流的观点。其中的方法就是不断地查找引用的和被引的文献。这个工作将会花费的时间是不可预计的。所以，如果时间有限，或者等着你出个报告的话，你不能太完美主义希望做个“好学生”。世界上这么多研究方向，每个都了解得很透彻是不可能的。既然“每个都”是不可能的，那透彻了解十个？透彻了解三个？——这都没有意义，完全是看你有多长寿和多感兴趣的问题。既然如此，不透彻就不透彻吧！错就错吧！你身边也许是有“学术牛人”，你很崇拜他，希望通过自己努力能向他靠拢，所以觉得还有努力的空间就不想放弃，尽量想多看几篇文献；但你不是永远做学生，在工作的人眼里“做个好学生”的标准简直是奢侈的，你们无限的时间就是用来学习。只要在学习没有在玩就是值得称赞的；特别是读研的，选择读研本身就是爱学习的表现，赞；还去读博？赞；学习无止境？赞……这导致你们学习没有deadline，你们做事没有deadline，你们把做事当作学习的机会，结果变成只学习不做事。“这件事情让我学到好多东西啊，一开始我不知道什么是XXX，我查了很多，发现原来XXX还有YYY，其实呢，最早的YYY是来自1895年……”你写出一篇Wiki是没人赞你的；你时间误了的话，请离职。

所以，哪怕你将来想以科研为职业，我也建议你参加一下外企在校园里招聘的“管理实习生培训生XX营俱乐部”之类，见见世面，留意一下邮件格式电话礼仪办事联系确定人员开会流程方法之类，别太宅了，不然很容易变成Loser。

** 回答3
心理学认为，兴趣是一种情绪，而情绪，是人类进化出来的一种生存工具。这种情绪能够穿过百万年的进化留下来，一定是因为其有莫大的好处。

先来了解一下兴趣是如何产生的？

看看下面这幅图，你觉得哪一个多边形最有趣？哪一个最让你愉悦？


这是心理学家Berlyne关于有趣的一个实验，实验中出现的多边形没有任何的特定意义，由计算机按照不同的复杂程度随机生成，越往后面，复杂度越高。Berlyne发现大部分人的最有趣选项在第三排中，这一组复杂程度让人一眼看不懂，从而产生各种联想——在我看来，左边像仙鹤，中间的像一个发出闪电的老巫师，右边的像一个跳麦克杰克逊舞蹈的树人。但是当选择最让你愉悦的一个时候，情况却有所改变，大部分人选择了第一排，最简单的这几个。

其中复制的数据筛选与分析过程跳过，实验有个清晰的结论：

有趣（Interested）是一种和不确定相关很高的情绪；

愉悦（Comfor）是一种和确定性相关很高的情绪；

而有趣和愉悦，是两个完全不同，甚至相反的情绪——当一个事情复杂、新奇和不确定的时候，人们就会感到有趣；而当一个事情简单、稳定和确定的时候，我们就会感觉到愉悦。愉悦的事情，不一定有趣，而有趣的事情，不一定会愉悦。变态辣鸡翅有趣而羊肉串愉悦；狐狸精有趣而良家妇女愉悦。创业有趣而公务员愉悦。

好生活=愉悦+有趣

你有没有发现世界上有两种不同的人？——有人总是去新馆子、点新菜，尝试更多口味。而有些人喜欢去老饭店，点上家常菜，吃的安安稳稳。比如旅游，有人喜欢探险，去穷山恶水异国他乡；有人喜欢休闲，往水清沙幼舒适恬静。前者有趣，后者愉悦，好的生活则应该是愉悦又有趣。

我们的生活也有这两部分。

我们满身疲惫的关上电脑，完成一项有价值的工作、我们在街上遇到熟悉的老同学、我们呆在老家的老房子里晒太阳、我们与家人挤在沙发上看最老版的《西游记》、我们接近大自然、我们在春节挤上拥挤的火车回家——这可一点都不有趣——但是这些事情让我们心跳放慢，血压降低，内心宁静。他们温暖、简单、安全，带给我们幸福与愉悦的感觉。

当我们接到一个全新的挑战性任务、我们在街上遇到一个跳舞的街头艺人，我们站在一个全新的繁华都市的入口，我们和旅途上遇到个一见如故的陌生人，彻夜长谈；我们决定要探险穿过一片森林，这都让我们心跳加速、手心发汗、同时让我们也觉得新奇复杂，有趣。

好的生活应该是愉悦又有趣。

动画片的设计最能说明这个问题，为了让注意力很短的孩子们坐在银幕前一个多小时，虽然没有心理学知识，动画片大师都直觉般使用了这个愉悦+有趣的模式：在大部分的动画中，总有一个复杂、新奇、或神秘或搞怪的二号，同时又有一个直接、温暖、简单的主角，如驴子和史莱克，流川枫和樱木花道，佐助和鸣人，豪猪和小狮子王，所以这些动画片即愉悦又有趣。

兴趣是成长的催化剂

好奇心害死猫，安安稳稳多好，人类为什么要还有“感兴趣”这种奇怪的设定？进化心理学发现，兴趣是一种应对成长中“不确定”的情绪——当我们遇到了“不确定”，我们会下意识的躲回自己的舒适区寻求“愉悦”。因为所有的成长都来自舒适区之外，这样一来我们永远也无法成长。这时候“有趣”的情绪会出现，帮我们度过难关——我们大脑跑出来个小人勾引：“多好玩啊，要不试试看？”于是我们继续前进，越过那些不确定。兴趣鼓励我们走出安全区，让我们变得越来越强，而世界变得越来越大。

大人把孩子抛起来玩耍，孩子会先有些恐惧，但是一旦被接住，他就会咯吱咯吱的大笑，笑声像广场飞起来的鸽子。几次以后，孩子只要一被抛起来，就呵呵的乐，他开始穿越这种不确定性的恐惧，觉得有趣，他的勇气变得更大，他的信任变强。兴趣是这个成长的催化剂。

有趣和愉悦的界限，在于“不确定性”的程度。过度不确定的生活毫无愉悦可言，充满焦虑；而一旦不确定太少，日子又无趣得很，日复一日能淡出个鸟来。有智慧的人懂得调配出适合自己的“不确定”。有趣如菜里的盐，而愉悦如菜本身。如懂得调配得当，管自己、做项目、办公司，治大国如烹小鲜。

好的生活应该是愉悦加有趣，适当不确定。但是很多人有对于“感兴趣”的事情保有幻想，他们认为感兴趣的事情应该是特别快乐、舒适、天生就会的。有这种信念的人把自己玩得很惨——他们终身寻找自己“感兴趣”的事情，一旦遇到困难与不确定，就声称自己“不感兴趣”然后闪人，寻找下一个“感兴趣”的事情。其实他要的不是兴趣，而是愉悦。

这个愉悦/兴趣比对于职业发展也相当重要。很多人来找职业规划师，说：“我不喜欢我的工作。”却不知道自己到底活得不愉悦，还是无趣？如果是不愉悦，他们则需要做减法，找到核心价值，降低其他目标，进入一个相对更简单、清晰的职业环境中去，而如果无趣则需要做加法——提高一些难度，或让自己进入更复杂、更不确定的职业环境。很多人只想活的愉悦舒服些，却给自己挖了个更大的坑跳进去，结果更痛苦了。

我遇到过一位外企销售经理，收入高且稳定，觉得工作无趣。在价值观的排列中，他认为最重要的是“利他助人”和“社会家人认同”。他觉得规划师的工作很有趣，执意希望成为其一。但职业规划师不是个简单的职业，需要至少200小时的系统学习和操练，才能让一个有职场经验的人成为合格的咨询师。在此投资期间还甚少经济回报，他同样很看重的“经济报酬”会大打折扣，这很不那么让人愉悦。听到这里，他的脸抽动了一下。

我再进一步告诉他，这200小时也充满了不确定性——读书拿证还好办，第一次咨询的灰头土脸，第一次讲课的一片死寂，训练营里高强度的极限挑战，写案例被督导说得一无是处，最后还需要通过PK才开始授课，即使这样，也不是一个结束，开始讲课后看到打分的惶惶不安，咨询后的反复揣摩，依然会伴随你好几年——这条道路充满这么多不确定的时候——你还觉得有趣吗？

听完我的讲述，这位兄弟顿时觉得规划师不那么有趣了，心算完收益产出比以后，他还是觉得他的一个创业项目比较有趣——因为那个不确定性，没有那么大。他可以同时保持自己的愉悦与有趣。

像这位仁兄一样，我们常常因为白饭吃多了，就以为自己要以腐乳为生。我把这种现象称为：“火锅效应”——如果你问一个天天吃家常菜的人说你想吃点什么？他会说，火锅！我最爱吃火锅！但是如果你抓他吃一个月的火锅——哪怕变着花样，他估计哭着喊着要回家。最好的生活，是经常吃米饭，偶尔点火锅。

如果你真的希望生活过得特有趣，让我告诉你兴趣的真相——兴趣不是那件让你舒舒服服就成功拿到结果的事，兴趣是那件让你白天痛苦的想、晚上睡不好、早上五点爬起来，一边苦笑着骂娘一边咧着嘴干完的事情。那才是兴趣本来的样子。

本文摘选自古典老师新书《你的生命有什么可能》

如果你曾《拆掉思维里的墙》，那你一定想看看《你的生命有什么可能》
