;; emacs lisp remove whitespace tab in current line

(defun remove-whitespace-tab-current-line()
  (interactive)
  (let* ((current-line-string (if (region-active-p)
								  (buffer-substring-no-properties (region-beginning) (region-end))
								(buffer-substring-no-properties (line-beginning-position) (line-end-position))))
		 (replace-string (replace-regexp-in-string "[:*\t ]+" "" current-line-string)))
	(delete-region (line-beginning-position) (line-end-position))
	(insert replace-string)))

(defun remove-whitespace-tab-current-line()
  (interactive)
  (let* ((start-point (if (region-active-p)
						  (region-beginning)
						(line-beginning-position)))
		 (end-point (if (region-active-p)
						(region-end)
					  (line-end-position)))
		 (origin-string (buffer-substring-no-properties start-point end-point))
		 (result-string (replace-regexp-in-string "[:*\t ]+" "" origin-string)))
	(delete-region start-point end-point)
	(insert result-string)))
